libxml2/VITABUILD
libxml2/patches/libxml2-2.9.4-vita.patch
travis_packages.sh

Note: Add ${VITASDK}/arm-vita-eabi/include/libxml2 to your includes

Add libxml2

---

speexdsp/VITABUILD
travis_packages.sh

Added speexdsp.

---

pixman/VITABUILD
travis_packages.sh

Added pixman.

---

kuio/VITABUILD

Added kuio package, i don't have a working vdpm installed here to be sure that it works as intended. Let me know if i have to change something.

Added kuio package.

---

mpg123/VITABUILD
mpg123/mpg123.patch

Added mpg123.

---

TinyGL/VITABUILD
kuio/VITABUILD

Added TinyGL package. Don't know why, kuio commit has been included in the PR :/

Added TinyGL.

---

libzip/VITABUILD
libzip/libzip.patch
travis_packages.sh

Add libzip

---

taipool/VITABUILD
travis_packages.sh

Added taipool.

---

Box2D/VITABUILD
travis_packages.sh

Added Box2D.

---

libxml2/VITABUILD

Fix libxml2 build (hopefully)

---

libpng/VITABUILD
mpg123/VITABUILD
mpg123/mpg123.patch
zlib/VITABUILD

Update zlib, libpng and mpg123

---

minizip/VITABUILD
travis_packages.sh

Slightly hackish but it builds and tests complete.

Added Minizip

---

libtheora/VITABUILD

I made this to learn how to use the Vita SDK and in the hope of being able to build Love2D. Love has more dependencies, though, so I didn't get further with that. I thought this may be useful to others.

Add libtheora VITABUILD

---

jsoncpp/VITABUILD
travis_packages.sh

This is a nice library to use for reading json. There is an example for it which works on the Vita here: https://github.com/sharkwouter/jsoncpp-vita

Added jsoncpp

---

imgui-vita2d/VITABUILD
travis_packages.sh

an implementation of imgui using vita2d

add imgui-vita2d library

---

sdl2/VITABUILD

Now that vita port got upstreamed, i kinda dropped work on my patchset against latest release, so new features are now in upstream master.

Switch SDL2 to upstream git version

---

flac/VITABUILD

And remove patch about <memory.h> as it is no longer required

flac: update package to version 1.3.3

---

sdl2/VITABUILD

Provide gl-less sdl2 package by default.

Update SDL2 package

---

Box2D/VITABUILD
box2d/VITABUILD

Please not that this is build from latest box2d sources (stable release), headers location changed from version 3.x.x which could brake some homebrews (need to correct includes paths in homebrews).

box2d: add proper box2d package

---

TinyGL/VITABUILD
asio/VITABUILD
bullet/VITABUILD
cpython/VITABUILD
curl/VITABUILD
gifdec/VITABUILD
imgui-vita2d/VITABUILD
imgui/VITABUILD
kubridge/VITABUILD
kuio/VITABUILD
libbaremetal/VITABUILD
libdebugnet/VITABUILD
libftpvita/VITABUILD
libimagequant/VITABUILD
libk/VITABUILD
libmad/VITABUILD
libmathneon/VITABUILD
libmikmod/VITABUILD
libmodplug/VITABUILD
libvita2d/VITABUILD
libvita2d_ext/VITABUILD
libxml2/VITABUILD
openssl/VITABUILD
pib/VITABUILD
sdl2_net/VITABUILD
sdl_net/VITABUILD
sdl_ttf/VITABUILD
taipool/VITABUILD
vitaGL/VITABUILD
yaml-cpp/VITABUILD

Update git links to use git+https instead

Fix git links

---

libsigc++-2.0/VITABUILD
libsigc++-3.0/VITABUILD

yeah so like you can just build it for vita and it works,
needed for building mkxp. so figured i should just add it to the sdk

Add libsigc++2.0 and libsigc++3.0

---

physfs/VITABUILD

PHYSFS: set proper error-codes

---

libarchive/VITABUILD
libarchive/libarchive-3.3.2-vita.patch

libarchive was compiling fine but couldn't link (undefined reference to waitpid and such). 
Tested working on my nestopia (pnes) port.

libarchive: fix patch

---

websocketpp/VITABUILD
wslay/VITABUILD

Websocketpp requires boost https://github.com/vitasdk/packages/pull/198

Add websocketpp and wslay

---

assimp/VITABUILD
assimp/assimp-no-pic.patch

Tested with https://github.com/isage/vita-assimp-sample

Add assimp 5.2.4-1

---

sdl2_image/VITABUILD
sdl2_image/pkgconfig.patch
sdl2_mixer/VITABUILD
sdl2_mixer/pkgconfig.patch
sdl_image/VITABUILD
sdl_image/pkgconfig.patch
sdl_mixer/VITABUILD
sdl_mixer/pkgconfig.patch

Add dependencies to sdl satellite libs pkgconfig files.
@frangarcj docker image can be updated after merging this.

Fix sdl sattelites

---

un7zip/VITABUILD

This is a very simple "un-7zip" library that I created to extract 7z on my homebrew apps like Apollo.
(Probably not the most elegant solution, but simple enough if you just need to extract a `.7z`)

Add simple un7zip library

---

mbedtls/VITABUILD

This PR adds the mbedTLS library (based on the latest available version v3.2.1)

Add latest mbedTLS library

---

sdl2/VITABUILD

sdl2: fix build type

---

vita-rss-libdl/VITABUILD

Same as #227, just with requested changes. VDPM will need to be changed to make this the default

Add vita-rss-libdl (take two)

---

.github/workflows/build.yml
luajit/VITABUILD

Add LuaJIT-2.1

---

FluidLite/VITABUILD

FluidLite: set POSITION_INDEPENDENT_CODE to FALSE

---

mbedtls/VITABUILD

Incorrect usage of sed caused wiping files instead of changing them.
Ref: https://stackoverflow.com/questions/9893445/why-sed-replace-redirection-deletes-my-file

mbedtls: fix sed usage

---

.github/workflows/build.yml

Passes token to be used by https://github.com/vitasdk/vita-headers/pull/741

Pass token to github api

---

FluidLite/VITABUILD

See https://github.com/divideconcept/FluidLite/pull/43 and the related issue https://github.com/divideconcept/FluidLite/issues/42

FluidLite: use CMAKE_POSITION_INDEPENDENT_CODE

---

openal-soft/VITABUILD

https://openal-soft.org/ is down

openal-soft: fix source url

---

harfbuzz/VITABUILD

Update version and switch to cmake to build the harfbuzz

harfbuzz: update package to version 7.3.0

---

mbedtls/VITABUILD
mbedtls/vita.patch

mbedtls: update package to version 3.4.0

---

libtremor/VITABUILD
libtremor/asm_arm.diff

This fixes the build, but since there seem to be no projects using libtremor on vita it needs to somehow be tested

Fixed libtremor build

---

zlib/VITABUILD

It was failing to build, so I decided to throw a small update. This URL should stick around.

Update zlib package

---

assimp/VITABUILD

assimp: use minizip and zlib as depends

---

zstd/VITABUILD

- Use CMake to build
- Patch build files to disable POSITION_INDEPENDENT_CODE

zstd: update package to version 1.5.7
